---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/greeter/overlays/development
    repoURL: git@github.com:locurateam/gitops-talk-27-jul-2021.git
    targetRevision: fully-automated
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: thirdparties/redis/overlays/development
    repoURL: git@github.com:locurateam/gitops-talk-27-jul-2021.git
    targetRevision: fully-automated